# Generated by Django 2.2 on 2020-04-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200406_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='hostelmanager',
            name='contact',
        ),
    ]
