# Generated by Django 2.2 on 2020-05-31 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200528_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppt', to='api.Property'),
        ),
    ]
