# Generated by Django 3.0.6 on 2020-05-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200406_1053'),
        ('api', '0003_auto_20200507_1327'),
    ]

    operations = [
    ]
