# Generated by Django 2.2 on 2020-05-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200531_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='saved',
            field=models.ManyToManyField(related_name='properties', to='api.Saved'),
        ),
        migrations.AlterUniqueTogether(
            name='saved',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='saved',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='saved',
            name='property',
        ),
    ]
